---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    version: v1
  name: nginx-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      initContainers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx-init
        command: ["bash", "-c", "echo v1 > /usr/share/nginx/html/index.html"]
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - emptyDir: {}
        name: html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    version: v2
  name: nginx-v2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v2
  template:
    metadata:
      labels:
        app: nginx
        version: v2
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      initContainers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx-init
        command: ["bash", "-c", "echo v2 > /usr/share/nginx/html/index.html"]
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - emptyDir: {}
        name: html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
